name: Build Playground

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_playground:
    name: build-playground
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install ziglang
        run: python -m pip install ziglang==0.13.0

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14

      - name: Build libspy
        run: make -C spy/libspy TARGET=emscripten

      - name: Build Python wheel
        run: |
          python -m pip install --upgrade pip build
          python -m build --wheel

      - name: Update main.py with wheel filename
        run: |
          VERSION=$(python -c "import tomllib; print(tomllib.load(open('pyproject.toml', 'rb'))['project']['version'])")
          WHEEL_NAME="spylang-${VERSION}-py3-none-any.whl"
          sed -i "s|spylang-.*-py3-none-any\.whl|${WHEEL_NAME}|g" playground/main.py

      - name: Copy built files to playground
        run: |
          cp spy/libspy/build/emscripten/release/libspy.mjs playground/
          cp spy/libspy/build/emscripten/release/libspy.wasm playground/
          cp dist/spylang-*.whl playground/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './playground'

  deploy:
    name: deploy-to-pages
    runs-on: ubuntu-latest
    needs: build_playground
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
